# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'WebRtc_SRS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for WebRtc_SRS

	pod 'GoogleWebRTC'
	pod 'SnapKit'
  pod 'Alamofire'
  pod 'Toast-Swift'

end
